[package]
name = "arcanedepths_glam"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "arcanedepths_glam"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.28.0"
glam = { version = "0.24", default-features = false, features = ["libm"] }